version: '3.8'

services:
  app:
    image: javatimwork/txbank-app:beta
    container_name: txbank-app
    ports:
      - "8080:8080"
    command: sh -c "sleep 30 && java -jar /app/app.jar"
    depends_on:
      - mysql
      - mongo
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_YML}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI_YML}

  mysql:
    image: mysql:8
    container_name: txbank-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo
    container_name: txbank-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data: